services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.148.1
    container_name: victoriametrics
    restart: unless-stopped

    ports:
      - "8428:8428"

    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=7d"

    volumes:
      - vm_data:/storage

    networks:
      - observability


  opensearch:
    image: opensearchproject/opensearch:3.8.0
    container_name: opensearch
    restart: unless-stopped

    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"

    ports:
      - "9200:9200"
      - "9600:9600"

    volumes:
      - opensearch_data:/usr/share/opensearch/data

    networks:
      - observability


  grafana:
    image: grafana/grafana:12.4.0
    container_name: grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - victoriametrics
      - opensearch

    networks:
      - observability


  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.158.0
    container_name: otel-collector
    restart: unless-stopped

    command:
      - "--config=/etc/otelcol-contrib/config.yaml"

    user: "0"

    ports:
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "8888:8888"     # Collector metrics
      - "13133:13133"   # Health check

    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro

      # Cho phép Collector đọc filesystem của Ubuntu host.
      - /:/hostfs:ro

    depends_on:
      - victoriametrics
      - opensearch

    networks:
      - observability


networks:
  observability:
    driver: bridge


volumes:
  vm_data:
  opensearch_data:
  grafana_data: