apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: query-gateway-tls

spec:
  secretName: query-gateway-tls
  commonName: query-gateway

  duration: 2160h
  renewBefore: 360h

  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS8
    rotationPolicy: Always

  usages:
    - client auth

  issuerRef:
    name: observability-ca
    kind: Issuer