apiVersion: v1
kind: Service
metadata:
  name: vmstorage

spec:
  clusterIP: None

  selector:
    app: vmstorage

  ports:
    - name: vminsert
      port: 8400
      targetPort: vminsert

    - name: vmselect
      port: 8401
      targetPort: vmselect

    - name: http
      port: 8482
      targetPort: http
