apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless

spec:
  clusterIP: None
  publishNotReadyAddresses: true

  selector:
    app: opensearch

  ports:
    - name: transport
      port: 9300
      targetPort: transport
