apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../../base/foundation
  - ../../base/storage/victoriametrics
  - ../../base/storage/opensearch
  - ../../base/ingest/otel-gateway
  - ../../base/identity/keycloak
  - ../../base/query

secretGenerator:
  - name: opensearch-bootstrap
    envs:
      - secrets.env

  - name: opensearch-ingest
    envs:
      - opensearch-ingest.env

  - name: keycloak-db
    envs:
      - keycloak-db.env

  - name: keycloak-admin
    envs:
      - keycloak-admin.env

  - name: grafana-admin
    envs:
      - grafana-admin.env

  - name: grafana-oidc
    envs:
      - grafana-oidc.env

images:
  - name: query-gateway
    newName: kerafeng/query-gateway
    newTag: v0.1.1

patches:
  - path: patches/keycloak.yaml
